package com.kinchat.app.core.designsystem

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

data class ExtendedColors(
    // Bubble
    val bubbleSentBackground: Color,
    val bubbleSentText: Color,
    val bubbleReceivedBackground: Color,
    val bubbleReceivedText: Color,
    val bubbleTimestampSent: Color,
    val bubbleTimestampReceived: Color,
    val bubbleSelectedOverlay: Color,
    // Status
    val statusSent: Color,
    val statusDelivered: Color,
    val statusRead: Color,
    val statusFailed: Color,
    val statusPending: Color,
    // Presence
    val presenceOnline: Color,
    val presenceOffline: Color,
    val presenceAway: Color,
    val typingIndicator: Color,
    // Chat List
    val chatListDivider: Color,
    val chatListSelectedBackground: Color,
    val unreadBadgeBackground: Color,
    val unreadBadgeText: Color,
    val pinnedChatBackground: Color,
    val mutedChatIndicator: Color,
    val lastMessagePreview: Color,
    // Input
    val inputFieldBackground: Color,
    val inputFieldBorder: Color,
    val inputFieldBorderFocused: Color,
    val inputPlaceholder: Color,
    val sendButtonActive: Color,
    val sendButtonDisabled: Color,
    val attachmentIcon: Color,
    val micIconActive: Color,
    val micIconRecording: Color,
    // In-message
    val linkColor: Color,
    val mentionBackground: Color,
    val mentionText: Color,
    val reactionChipBackground: Color,
    val reactionChipSelectedBackground: Color,
    val quotedReplyBar: Color,
    val quotedReplyBackground: Color,
    val codeBlockBackground: Color,
    // System/Feedback
    val systemMessageBackground: Color,
    val systemMessageText: Color,
    val errorBanner: Color,
    val warningBanner: Color,
    val successBanner: Color,
    val disappearingMessageIndicator: Color,
    // Avatar
    val avatarColors: List<Color>,
    val avatarFallbackText: Color
)

val ExtendedColorsLight = ExtendedColors(
    bubbleSentBackground = BubbleSentBgLight,
    bubbleSentText = BubbleSentTextLight,
    bubbleReceivedBackground = BubbleReceivedBgLight,
    bubbleReceivedText = BubbleReceivedTextLight,
    bubbleTimestampSent = BubbleTimestampSentLight,
    bubbleTimestampReceived = BubbleTimestampReceivedLight,
    bubbleSelectedOverlay = BubbleSelectedOverlayLight,
    statusSent = StatusSentLight,
    statusDelivered = StatusDeliveredLight,
    statusRead = StatusReadLight,
    statusFailed = StatusFailedLight,
    statusPending = StatusPendingLight,
    presenceOnline = PresenceOnlineLight,
    presenceOffline = PresenceOfflineLight,
    presenceAway = PresenceAwayLight,
    typingIndicator = TypingIndicatorLight,
    chatListDivider = ChatListDividerLight,
    chatListSelectedBackground = ChatListSelectedBgLight,
    unreadBadgeBackground = UnreadBadgeBgLight,
    unreadBadgeText = UnreadBadgeTextLight,
    pinnedChatBackground = PinnedChatBgLight,
    mutedChatIndicator = MutedChatIndicatorLight,
    lastMessagePreview = LastMessagePreviewLight,
    inputFieldBackground = InputFieldBgLight,
    inputFieldBorder = InputFieldBorderLight,
    inputFieldBorderFocused = InputFieldBorderFocusedLight,
    inputPlaceholder = InputPlaceholderLight,
    sendButtonActive = SendButtonActiveLight,
    sendButtonDisabled = SendButtonDisabledLight,
    attachmentIcon = AttachmentIconLight,
    micIconActive = MicIconActiveLight,
    micIconRecording = MicIconRecordingLight,
    linkColor = LinkColorLight,
    mentionBackground = MentionBgLight,
    mentionText = MentionTextLight,
    reactionChipBackground = ReactionChipBgLight,
    reactionChipSelectedBackground = ReactionChipSelectedBgLight,
    quotedReplyBar = QuotedReplyBarLight,
    quotedReplyBackground = QuotedReplyBgLight,
    codeBlockBackground = CodeBlockBgLight,
    systemMessageBackground = SystemMessageBgLight,
    systemMessageText = SystemMessageTextLight,
    errorBanner = ErrorBannerLight,
    warningBanner = WarningBannerLight,
    successBanner = SuccessBannerLight,
    disappearingMessageIndicator = DisappearingMsgIndicatorLight,
    avatarColors = AvatarColors,
    avatarFallbackText = AvatarFallbackText
)

val ExtendedColorsDark = ExtendedColors(
    bubbleSentBackground = BubbleSentBgDark,
    bubbleSentText = BubbleSentTextDark,
    bubbleReceivedBackground = BubbleReceivedBgDark,
    bubbleReceivedText = BubbleReceivedTextDark,
    bubbleTimestampSent = BubbleTimestampSentDark,
    bubbleTimestampReceived = BubbleTimestampReceivedDark,
    bubbleSelectedOverlay = BubbleSelectedOverlayDark,
    statusSent = StatusSentDark,
    statusDelivered = StatusDeliveredDark,
    statusRead = StatusReadDark,
    statusFailed = StatusFailedDark,
    statusPending = StatusPendingDark,
    presenceOnline = PresenceOnlineDark,
    presenceOffline = PresenceOfflineDark,
    presenceAway = PresenceAwayDark,
    typingIndicator = TypingIndicatorDark,
    chatListDivider = ChatListDividerDark,
    chatListSelectedBackground = ChatListSelectedBgDark,
    unreadBadgeBackground = UnreadBadgeBgDark,
    unreadBadgeText = UnreadBadgeTextDark,
    pinnedChatBackground = PinnedChatBgDark,
    mutedChatIndicator = MutedChatIndicatorDark,
    lastMessagePreview = LastMessagePreviewDark,
    inputFieldBackground = InputFieldBgDark,
    inputFieldBorder = InputFieldBorderDark,
    inputFieldBorderFocused = InputFieldBorderFocusedDark,
    inputPlaceholder = InputPlaceholderDark,
    sendButtonActive = SendButtonActiveDark,
    sendButtonDisabled = SendButtonDisabledDark,
    attachmentIcon = AttachmentIconDark,
    micIconActive = MicIconActiveDark,
    micIconRecording = MicIconRecordingDark,
    linkColor = LinkColorDark,
    mentionBackground = MentionBgDark,
    mentionText = MentionTextDark,
    reactionChipBackground = ReactionChipBgDark,
    reactionChipSelectedBackground = ReactionChipSelectedBgDark,
    quotedReplyBar = QuotedReplyBarDark,
    quotedReplyBackground = QuotedReplyBgDark,
    codeBlockBackground = CodeBlockBgDark,
    systemMessageBackground = SystemMessageBgDark,
    systemMessageText = SystemMessageTextDark,
    errorBanner = ErrorBannerDark,
    warningBanner = WarningBannerDark,
    successBanner = SuccessBannerDark,
    disappearingMessageIndicator = DisappearingMsgIndicatorDark,
    avatarColors = AvatarColors,
    avatarFallbackText = AvatarFallbackText
)

val LocalExtendedColors = staticCompositionLocalOf { ExtendedColorsLight }
